### ISSUE TITLE
1.1.1 ? 

### ISSUE THREAD

**Issue by glilienthal** [Seancheey/FactorioBeltRouter#3]
I can run this on factorio 1.1.1. 

Is there a way I can ignore the settings and make it work anyway? 

Also, this is to tell you @Seancheey, how much I appreciate this mod and would be happy if I could run it on the newest factorio. 👍

**Comment by Seancheey** [comment]
Sure I can update the mod to 1.1 :) I'm on vacation right now, so will probably update in 3 days. Thanks for liking this mod :D

**Comment by Seancheey** [comment]
There is a info.json file containing version compatibility specs. You can change it yourself to match 1.1 I believe.

**Comment by glilienthal** [comment]
I tried, but somehow messed this up. I'll just wait for you to update this. :).

**Comment by Seancheey** [comment]
updated :D
